baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'tanjun'
title = "Felipe Martin's Site"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2
