baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'tanjun'
title = "Felipe Martin's Site"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3
